/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_integrador_ll_etapa4;

import javax.swing.JOptionPane;

/**
 *
 * @author Murilo
 */
public class Tela_Central extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Central
     */
    
    public Tela_Central() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botao_SacarDepositar = new javax.swing.JButton();
        Botao_Excluir = new javax.swing.JButton();
        Botao_Transacao = new javax.swing.JButton();
        Botao_AbrirConta = new javax.swing.JButton();
        Botao_FecharConta = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Botao_SacarDepositar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Botao_SacarDepositar.setText("Sacar/ Depositar");
        Botao_SacarDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SacarDepositarActionPerformed(evt);
            }
        });

        Botao_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Botao_Excluir.setText("Excluir Conta");
        Botao_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_ExcluirActionPerformed(evt);
            }
        });

        Botao_Transacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Botao_Transacao.setText("Transacoes Financeiras");
        Botao_Transacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_TransacaoActionPerformed(evt);
            }
        });

        Botao_AbrirConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Botao_AbrirConta.setText("Abrir Conta");
        Botao_AbrirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_AbrirContaActionPerformed(evt);
            }
        });

        Botao_FecharConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Botao_FecharConta.setText("Fechar Conta");
        Botao_FecharConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_FecharContaActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Atividades Conta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_FecharConta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botao_Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(Botao_Transacao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botao_SacarDepositar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_AbrirConta)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_SacarDepositar)
                    .addComponent(Botao_AbrirConta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_Excluir)
                    .addComponent(Botao_Transacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(Botao_FecharConta))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_SacarDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SacarDepositarActionPerformed
        Tela_SacarDepositar tsd = new Tela_SacarDepositar();
        tsd.setVisible(true);
    }//GEN-LAST:event_Botao_SacarDepositarActionPerformed

    private void Botao_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_ExcluirActionPerformed
        String i = JOptionPane.showInputDialog("Digite o Id da Conta");
        int id = Integer.parseInt(i);
        String r = JOptionPane.showInputDialog("Deseja Apagar essa conta? [S/N]");
        if(r.equals("S")){
          Tela_CriarConta.a[id] = null;
        }else{
            
        }
    }//GEN-LAST:event_Botao_ExcluirActionPerformed

    private void Botao_TransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_TransacaoActionPerformed
        Tela_Transacao tt = new Tela_Transacao();
        tt.setVisible(true);
    }//GEN-LAST:event_Botao_TransacaoActionPerformed

    private void Botao_AbrirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_AbrirContaActionPerformed
       String i = JOptionPane.showInputDialog("Digite o Id da Conta");
       int id = Integer.parseInt(i);
       conta c = Tela_CriarConta.a[id];
       c.setStatus(true);
       Tela_CriarConta.a[id] = c;
    }//GEN-LAST:event_Botao_AbrirContaActionPerformed

    private void Botao_FecharContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_FecharContaActionPerformed
        String i = JOptionPane.showInputDialog("Digite o Id da Conta");
        int id = Integer.parseInt(i);
        conta c = Tela_CriarConta.a[id];
       c.setStatus(false);
       Tela_CriarConta.a[id] = c;
    }//GEN-LAST:event_Botao_FecharContaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Tela_Listagem tl = new Tela_Listagem();
        tl.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Central().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_AbrirConta;
    private javax.swing.JButton Botao_Excluir;
    private javax.swing.JButton Botao_FecharConta;
    private javax.swing.JButton Botao_SacarDepositar;
    private javax.swing.JButton Botao_Transacao;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
